apiVersion: v1
kind: Pod
metadata:
  name: argocd-test
  annotations:
    xfabric.kubernetes.io/secret-manager: vault
    xfabric.kubernetes.io/secret-service-tag-value: argocd-test
    xfabric.kubernetes.io/vault-mount: secret
  labels:
    app: argocd-test
spec:
  containers:
  - name: argocd-test
    env:
    - name: HTTP_PORT
      value: "9999"
    image: argocd-test:v0.1.0
    imagePullPolicy: Never
  serviceAccountName: argocd-test
