apiVersion: apps/v1
kind: Pod
metadata:
  name: argocd-test
  annotations:
    xfabric.kubernetes.io/secret-manager: vault
    xfabric.kubernetes.io/secret-service-tag-value: argocd-test
    xfabric.kubernetes.io/vault-mount: secret
spec:
  containers:
  - name: argocd-test
    image: argocd-test:0.1.0
